# Generated by Django 6.0.1 on 2026-01-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Например: 'Основной рецепт', 'Для вождения'", max_length=100, verbose_name='Название')),
                ('prescription_type', models.CharField(choices=[('glasses', 'Очки'), ('contacts', 'Контактные линзы')], default='glasses', max_length=20, verbose_name='Тип рецепта')),
                ('od_sph', models.DecimalField(blank=True, decimal_places=2, help_text='Сфера правого глаза, от -20.00 до +20.00', max_digits=5, null=True, verbose_name='OD SPH (сфера)')),
                ('od_cyl', models.DecimalField(blank=True, decimal_places=2, help_text='Цилиндр правого глаза для коррекции астигматизма', max_digits=5, null=True, verbose_name='OD CYL (цилиндр)')),
                ('od_axis', models.PositiveSmallIntegerField(blank=True, help_text='Ось цилиндра правого глаза, от 0 до 180 градусов', null=True, verbose_name='OD AXIS (ось)')),
                ('od_add', models.DecimalField(blank=True, decimal_places=2, help_text='Аддидация для прогрессивных/бифокальных линз', max_digits=4, null=True, verbose_name='OD ADD (аддидация)')),
                ('od_bc', models.DecimalField(blank=True, decimal_places=2, help_text='Базовая кривизна для контактных линз', max_digits=4, null=True, verbose_name='OD BC (базовая кривизна)')),
                ('od_dia', models.DecimalField(blank=True, decimal_places=2, help_text='Диаметр контактной линзы', max_digits=4, null=True, verbose_name='OD DIA (диаметр)')),
                ('os_sph', models.DecimalField(blank=True, decimal_places=2, help_text='Сфера левого глаза, от -20.00 до +20.00', max_digits=5, null=True, verbose_name='OS SPH (сфера)')),
                ('os_cyl', models.DecimalField(blank=True, decimal_places=2, help_text='Цилиндр левого глаза для коррекции астигматизма', max_digits=5, null=True, verbose_name='OS CYL (цилиндр)')),
                ('os_axis', models.PositiveSmallIntegerField(blank=True, help_text='Ось цилиндра левого глаза, от 0 до 180 градусов', null=True, verbose_name='OS AXIS (ось)')),
                ('os_add', models.DecimalField(blank=True, decimal_places=2, help_text='Аддидация для прогрессивных/бифокальных линз', max_digits=4, null=True, verbose_name='OS ADD (аддидация)')),
                ('os_bc', models.DecimalField(blank=True, decimal_places=2, help_text='Базовая кривизна для контактных линз', max_digits=4, null=True, verbose_name='OS BC (базовая кривизна)')),
                ('os_dia', models.DecimalField(blank=True, decimal_places=2, help_text='Диаметр контактной линзы', max_digits=4, null=True, verbose_name='OS DIA (диаметр)')),
                ('pd', models.DecimalField(blank=True, decimal_places=1, help_text='Расстояние между зрачками в мм', max_digits=4, null=True, verbose_name='PD (межзрачковое расстояние)')),
                ('pd_left', models.DecimalField(blank=True, decimal_places=1, help_text='Полумежзрачковое расстояние слева', max_digits=4, null=True, verbose_name='PD левый')),
                ('pd_right', models.DecimalField(blank=True, decimal_places=1, help_text='Полумежзрачковое расстояние справа', max_digits=4, null=True, verbose_name='PD правый')),
                ('doctor_name', models.CharField(blank=True, help_text='ФИО врача, выписавшего рецепт', max_length=200, verbose_name='Врач')),
                ('clinic_name', models.CharField(blank=True, help_text='Название клиники', max_length=200, verbose_name='Клиника')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата осмотра')),
                ('expiry_date', models.DateField(blank=True, help_text='Рецепт обычно действителен 1-2 года', null=True, verbose_name='Срок действия')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_primary', models.BooleanField(default=False, help_text='Использовать по умолчанию при заказе', verbose_name='Основной рецепт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
