# Generated by Django 6.0.1 on 2026-01-21 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'Acuvue Oasys', 'Основные линзы'", max_length=100, verbose_name='Название')),
                ('lens_type', models.CharField(choices=[('daily', 'Однодневные'), ('weekly', 'Недельные'), ('biweekly', 'Двухнедельные'), ('monthly', 'Месячные'), ('quarterly', 'Квартальные'), ('custom', 'Свой срок')], default='monthly', max_length=20, verbose_name='Тип линз')),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text='Укажите количество дней, если выбран свой срок', null=True, verbose_name='Свой срок (дней)')),
                ('start_date', models.DateField(help_text='Когда вы начали носить эту пару линз', verbose_name='Дата начала ношения')),
                ('notify_days_before', models.PositiveSmallIntegerField(default=1, help_text='За сколько дней до замены напомнить', verbose_name='Напоминать за (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Напоминание о замене линз',
                'verbose_name_plural': 'Напоминания о замене линз',
                'ordering': ['start_date'],
            },
        ),
    ]
