# Generated by Django 5.0.8 on 2026-01-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Например: about, contacts, delivery', max_length=120, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (H1)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секции (H2)')),
                ('body', models.TextField(blank=True, help_text='Можно несколько абзацев. Разделяйте абзацы пустой строкой.', verbose_name='Текст')),
                ('bullets', models.TextField(blank=True, help_text='Один пункт на строку. Если заполнено — на фронте будет <ul>.', verbose_name='Список (пункты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ('order', 'id'),
            },
        ),
    ]
