# Generated by Django 5.0.8 on 2026-01-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Например: about, contacts, delivery', max_length=120, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page', verbose_name='Страница'),
        ),
    ]
