# Generated by Django 5.0.8 on 2026-01-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, help_text="Отображать на странице 'Распродажа'", verbose_name='Распродажа'),
        ),
    ]
