# Generated by Django 5.0.8 on 2026-01-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('sort', 'id'), 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Показывать в фильтрах')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('slug', models.SlugField(max_length=120)),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'ordering': ('sort', 'value'),
                'unique_together': {('attribute', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Оставьте пустым для использования цены товара', max_digits=12, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('category', models.ForeignKey(blank=True, help_text='Оставьте пустым для глобальных вариаций', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_types', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип вариации',
                'verbose_name_plural': 'Типы вариаций',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('slug', models.SlugField(max_length=120)),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.variationtype', verbose_name='Тип вариации')),
            ],
            options={
                'verbose_name': 'Опция вариации',
                'verbose_name_plural': 'Опции вариаций',
                'ordering': ('sort', 'value'),
                'unique_together': {('variation_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalog.product', verbose_name='Товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributevalue', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Атрибут товара',
                'verbose_name_plural': 'Атрибуты товаров',
                'unique_together': {('product', 'attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='catalog.productvariant', verbose_name='Вариант')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variationoption', verbose_name='Опция')),
            ],
            options={
                'verbose_name': 'Опция варианта',
                'verbose_name_plural': 'Опции вариантов',
                'unique_together': {('variant', 'option')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный выбор')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_types', to='catalog.product', verbose_name='Товар')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variationtype', verbose_name='Тип вариации')),
            ],
            options={
                'verbose_name': 'Тип вариации товара',
                'verbose_name_plural': 'Типы вариаций товаров',
                'ordering': ('sort',),
                'unique_together': {('product', 'variation_type')},
            },
        ),
    ]
