# Generated by Django 5.0.8 on 2026-01-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_attribute_slug_alter_attributevalue_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariantoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productvariantoption',
            name='variant',
        ),
        migrations.AlterUniqueTogether(
            name='productvariationtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariationtype',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariationtype',
            name='variation_type',
        ),
        migrations.AlterUniqueTogether(
            name='variationoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variationoption',
            name='variation_type',
        ),
        migrations.RemoveField(
            model_name='variationtype',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Вариация товара', 'verbose_name_plural': 'Вариации товара'},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.AddField(
            model_name='attribute',
            name='show_in_product_card',
            field=models.BooleanField(default=True, help_text='Атрибут будет показан для выбора вариации в карточке товара', verbose_name='Показывать в карточке товара'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='catalog.attributevalue', verbose_name='Значения атрибутов'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='is_filterable',
            field=models.BooleanField(default=True, help_text='Атрибут будет доступен для фильтрации товаров в каталоге', verbose_name='Показывать в фильтрах каталога'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute', verbose_name='Атрибут')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributevalue', verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значение атрибута товара',
                'verbose_name_plural': 'Значения атрибутов товара',
                'unique_together': {('product', 'attribute_value')},
            },
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductVariantOption',
        ),
        migrations.DeleteModel(
            name='ProductVariationType',
        ),
        migrations.DeleteModel(
            name='VariationOption',
        ),
        migrations.DeleteModel(
            name='VariationType',
        ),
    ]
