# Generated by Django 5.0.8 on 2026-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_options_category_image_category_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_attributes',
            field=models.ManyToManyField(blank=True, help_text="Что показывать в блоке 'Характеристики'. Если пусто — покажем все атрибуты, кроме вариационных.", related_name='products_specs', to='catalog.attribute', verbose_name='Атрибуты характеристик'),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_attributes',
            field=models.ManyToManyField(blank=True, help_text='Какие атрибуты пользователь выбирает для подбора вариации (SPH/CYL/AXIS и т.п.)', related_name='products_variations', to='catalog.attribute', verbose_name='Атрибуты вариаций'),
        ),
    ]
