# Generated by Django 5.0.8 on 2026-01-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_spec_attributes_product_variation_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_attributes',
            field=models.ManyToManyField(blank=True, help_text='Если выбрано — в фильтрах каталога для этой категории показываем только эти атрибуты. Если пусто — используем глобальные Attribute.is_filterable.', related_name='categories_filter', to='catalog.attribute', verbose_name='Атрибуты фильтров для категории'),
        ),
    ]
