# Generated by Django 6.0.1 on 2026-01-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productvariant_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Для неавторизованных пользователей или если пользователь хочет оставить другое имя', max_length=100, verbose_name='Имя автора')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка от 1 до 5', verbose_name='Оценка')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('advantages', models.TextField(blank=True, verbose_name='Достоинства')),
                ('disadvantages', models.TextField(blank=True, verbose_name='Недостатки')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Пользователь купил этот товар', verbose_name='Подтверждённая покупка')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Полезно')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='Не полезно')),
                ('admin_response', models.TextField(blank=True, verbose_name='Ответ магазина')),
                ('admin_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='catalog_rev_product_eb69b9_idx'), models.Index(fields=['user'], name='catalog_rev_user_id_82176f_idx'), models.Index(fields=['status', 'created_at'], name='catalog_rev_status_b37478_idx')],
            },
        ),
    ]
