# Generated by Django 6.0.1 on 2026-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mega_menu_attributes',
            field=models.ManyToManyField(blank=True, help_text='Какие атрибуты показывать в мегаменю для этой категории (например 1–3). Если не выбрано — в мегаменю фильтры не показываем.', related_name='categories_mega_menu', to='catalog.attribute', verbose_name='Атрибуты мегаменю'),
        ),
    ]
