# Generated by Django 6.0.1 on 2026-01-27 12:40

from django.db import migrations


def deactivate_uncategorized(apps, schema_editor):
    """
    Деактивирует категории типа "Uncategorized" или пустые категории.
    """
    Category = apps.get_model('catalog', 'Category')

    # Ищем категории с названием или slug содержащим "uncategorized"
    uncategorized_slugs = ['uncategorized', 'bez-kategorii', 'без-категории']

    # Деактивируем по slug
    updated_count = Category.objects.filter(
        slug__in=uncategorized_slugs,
        is_active=True
    ).update(is_active=False)

    # Деактивируем по имени (case-insensitive)
    for cat in Category.objects.filter(is_active=True):
        if 'uncategorized' in cat.name.lower() or 'без категории' in cat.name.lower():
            cat.is_active = False
            cat.save(update_fields=['is_active'])
            updated_count += 1

    if updated_count > 0:
        print(f"Деактивировано категорий: {updated_count}")


def reactivate_uncategorized(apps, schema_editor):
    """
    Обратная миграция - активирует обратно категории uncategorized.
    """
    Category = apps.get_model('catalog', 'Category')
    uncategorized_slugs = ['uncategorized', 'bez-kategorii', 'без-категории']

    Category.objects.filter(slug__in=uncategorized_slugs).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_category_is_active'),
    ]

    operations = [
        migrations.RunPython(deactivate_uncategorized, reactivate_uncategorized),
    ]
