# Generated by Django 6.0.1 on 2026-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_deactivate_uncategorized_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters_enabled', models.BooleanField(default=True, help_text='Глобальное включение/отключение всех фильтров в каталоге', verbose_name='Фильтры включены')),
                ('show_attribute_count', models.BooleanField(default=True, help_text='Показывать количество товаров рядом с каждым значением атрибута в фильтрах', verbose_name='Показывать кол-во товаров в атрибутах')),
                ('show_category_count', models.BooleanField(default=True, help_text='Показывать количество товаров рядом с каждой категорией', verbose_name='Показывать кол-во товаров в категориях')),
                ('show_brand_count', models.BooleanField(default=True, help_text='Показывать количество товаров рядом с каждым брендом', verbose_name='Показывать кол-во товаров в брендах')),
                ('max_attribute_values', models.PositiveIntegerField(default=5, help_text="Сколько значений атрибута показывать до кнопки 'Показать все'", verbose_name='Макс. значений атрибута')),
                ('max_categories', models.PositiveIntegerField(default=5, help_text="Сколько категорий показывать до кнопки 'Показать все'", verbose_name='Макс. категорий')),
                ('max_brands', models.PositiveIntegerField(default=5, help_text="Сколько брендов показывать до кнопки 'Показать все'", verbose_name='Макс. брендов')),
            ],
            options={
                'verbose_name': 'Настройки каталога',
                'verbose_name_plural': 'Настройки каталога',
            },
        ),
    ]
