# Generated by Django 6.0.1 on 2026-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_add_catalog_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='brand',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
