# Generated by Django 5.0.8 on 2026-01-12 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('optometrist', 'Оптометрист')], max_length=30)),
                ('desired_datetime', models.DateTimeField()),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent_to_bitrix', 'Sent'), ('bitrix_failed', 'Failed')], default='new', max_length=30)),
                ('bitrix_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
