# Generated by Django 5.0.8 on 2026-01-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запись на приём', 'verbose_name_plural': 'Записи на приём'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='bitrix_raw',
            field=models.JSONField(blank=True, help_text='Сырой ответ от Bitrix24 API', null=True, verbose_name='Ответ Bitrix24'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='desired_datetime',
            field=models.DateTimeField(verbose_name='Желаемые дата и время'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('ophthalmologist', 'Офтальмолог'), ('optometrist', 'Оптометрист')], max_length=30, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('sent_to_bitrix', 'Отправлена в Bitrix24'), ('bitrix_failed', 'Ошибка отправки в Bitrix24')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
