# Generated by Django 6.0.1 on 2026-02-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
    ]
